"""add columns to table

Revision ID: 455f20a8ef8f
Revises: 67f5d67aea55
Create Date: 2024-07-06 22:00:07.968476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455f20a8ef8f'
down_revision = '67f5d67aea55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants')
    # ### end Alembic commands ###
