"""add column id to table

Revision ID: 888a4f04b59e
Revises: 455f20a8ef8f
Create Date: 2024-07-06 22:10:06.254796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888a4f04b59e'
down_revision = '455f20a8ef8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
